prefix db-owl: <http://dbpedia.org/ontology/>
#prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select  distinct *
where {
  service <http://fr.dbpedia.org/sparql/> {
     select    ?abstract   (group_concat(distinct ?label   ; separator = " | ") AS ?nameArtist)     
	?abstract   (group_concat(distinct ?bandMember    ; separator = " | ") AS ?uriArtist)     
	?abstract   (group_concat(distinct ?labelFormer    ; separator = " | ") AS ?formerArtist)    
	?abstract   (group_concat(distinct ?formerBandMember    ; separator = " | ") AS ?uriFormerArtist)   
     where {
	<http://fr.dbpedia.org/resource/Metallica> 	db-owl:abstract ?abstract ;
				 	db-owl:bandMember ?bandMember ;
					db-owl:activeYearsStartYear ?activeYearsStartYear  ;
					db-owl:formerBandMember ?formerBandMember .
	?formerBandMember 	rdfs:label   ?labelFormer
	?bandMember 	rdfs:label   ?label
	FILTER langMatches(lang(?label), 'en')
	FILTER langMatches(lang(?labelFormer), 'en')
	FILTER langMatches(lang(?abstract), 'en')
     } 
  }
}